### ISSUE TITLE
Spectral/flux coordinates did not display in SED Viewer. Error bars drawn incorrectly in Co-plot mode. [VAOPD-899]

### ISSUE THREAD

**Issue by olaurino** [olaurino/iris_restored#6]
#6 Issue by **jbudynk**, created on: 2014-05-19T16:06:43Z

I opened up three new SEDs from NED (m82, m87 and ngc7714) and co-plotted them all together. I noticed that the error bars for m87 and ngc7714 were very large (however this could be because m82 has a higher flux than the other two SEDs, and thus in log-log space, the m87 and ngc7714 error bars look much larger than they are). Because of this possible inconsistency with the error bars, I switched between co-plot and single-plot display mode to investigate. This is when I noticed that the coordinates were not showing up in the X and Y coordinate boxes on the top of the Viewer.

I restarted Iris to see if this would fix all of my problems, and it did. Now the error bars and X/Y coordinate displays are working correctly. I have not been able to reproduce the problem, and this has happened just once.

The following error message appeared in the command window at some point while running Iris. I was not aware of the error message until just after I exited Iris from the Iris desktop:

Exception in thread "Thread-4" java.lang.NullPointerException
at spv.graphics.ZoomUtilities.DoZoom(Unknown Source)
at spv.graphics.ZoomUtilities.ComputeZoomedViewport(Unknown Source)
at spv.graphics.WCSBoxCanvas.wheelBasedZoom(Unknown Source)
at spv.graphics.WCSBoxCanvas.update(Unknown Source)
at java.util.Observable.notifyObservers(Observable.java:159)
at java.util.Observable.notifyObservers(Observable.java:115)
at spv.graphics.WCSCursor.notifyAllObservers(Unknown Source)
at spv.graphics.WCSCursor.access$300(Unknown Source)
at spv.graphics.WCSCursor$BufferObserver.run(Unknown Source)
at java.lang.Thread.run(Thread.java:722)

If you need more info, just ask, but this is basically all I did in this Iris session. Thanks!

**Comment by olaurino** [comment]
Comment by **jbudynk**, created on: 2014-05-19T16:07:23Z

Since this is a Viewer issue, I am reassigning the ticket to Ivo.

**Comment by olaurino** [comment]
Comment by **jbudynk**, created on: 2014-05-19T16:07:37Z

I cannot reproduce the behavior either. From the description and the stack dump, I would guess it is some timing issue in the Java graphics thread that is causing this. I can blindly add a few traps in the code to hopefully catch the exception and ignore it. Apart from that, can't do much without the ability to consistently reproduce the behavior.

Anybody else has seen this kind of bug?

I will deliver a new jar file with the traps in place.

**Comment by olaurino** [comment]
Comment by **jbudynk**, created on: 2014-05-19T16:07:52Z

we had the OK to release Iris 2.0 yesterday. We are not in the new development cycle yet, so there is no rush, and we won't be able to test any patches in the short term.

**Comment by olaurino** [comment]
Comment by **jbudynk**, created on: 2014-05-19T16:08:00Z

Cool. I'll work on this when I get the time anyway
